// ListOfOrchids.js
export const dataOrchid = [
  {
    id: '1',
    name: 'Taichung Beauty',
    rating: 5,
    isSpecial: true,
    image: 'https://barritaorchids.com/cdn/shop/products/Cf592_1024x1024.jpg',
    color: 'pink',
    origin: 'Taiwan',
    category: 'Cattleya',
    info: 'A beautiful pink orchid originating from Taiwan, admired for its vibrant colors and fragrance.',
    cost: 100
  },
  {
    id: '2',
    name: 'Golden Sunset',
    rating: 4.5,
    isSpecial: false,
    image: 'https://media.istockphoto.com/id/481825589/photo/golden-sunset-orchid-latin-name-cymbidium-patarak.jpg?s=1024x1024&w=is&k=20&c=rt7LT7-j8oo3gmGP-FqWN7AdlPKEAlSz4ffbWkKbjbw=',
    color: 'yellow',
    origin: 'Thailand',
    category: 'Dendrobium',
    info: 'A stunning yellow orchid with a warm glow, native to Thailand and popular for its durability.',
    cost: 300
  },
  {
    id: '3',
    name: 'Moonlit Pearl',
    rating: 5,
    isSpecial: true,
    image: 'https://images.fineartamerica.com/images-medium-large-5/moonlit-orchid-karl-barth.jpg',
    color: 'white',
    origin: 'Japan',
    category: 'Cymbidium',
    info: 'This elegant white orchid is prized for its pearl-like petals and delicate fragrance.',
    cost: 500
  },
  {
    id: '4',
    name: 'Lavender Mist',
    rating: 4,
    isSpecial: false,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQha4l33kL7uA9K0To-0mirbicSe4wB8cKwmQ&s',
    color: 'purple',
    origin: 'India',
    category: 'Vanda',
    info: 'A captivating purple orchid with soft hues, originating from the tropical regions of India.',
    cost: 93
  },
  {
    id: '5',
    name: 'Scarlet Flame',
    rating: 5,
    isSpecial: true,
    image: 'https://www.kingfisherorchidnursery.com.au/cdn/shop/files/hsinying_scarlet_flame_dance_1024x1024.jpg?v=1721371639',
    color: 'red',
    origin: 'Brazil',
    category: 'Cattleya',
    info: 'A fiery red orchid from Brazil, celebrated for its intense color and bold appearance.',
    cost: 2300
  },
  {
    id: '6',
    name: 'Emerald Glow',
    rating: 4.8,
    isSpecial: false,
    image: 'https://www.picturethisgallery.com/wp-content/uploads/Emerald-Glow-Orchid-Dennis-Magnusson.jpg',
    color: 'green',
    origin: 'Colombia',
    category: 'Oncidium',
    info: 'A rare green orchid that glows with a unique charm, originating from the lush forests of Colombia.',
    cost: 47
  },
  {
    id: '7',
    name: 'Snow Queen',
    rating: 5,
    isSpecial: true,
    image: 'https://garden.org/pics/2018-09-22/Australis/101591.jpg',
    color: 'white',
    origin: 'Australia',
    category: 'Phalaenopsis',
    info: 'A regal white orchid with pristine petals, often associated with purity and grace.',
    cost: 50
  },
  {
    id: '8',
    name: 'Blazing Star',
    rating: 4.7,
    isSpecial: false,
    image: 'https://www.whiteflowerfarm.com/mas_assets/cache/image/8/9/e/7/35303.Jpg',
    color: 'orange',
    origin: 'Mexico',
    category: 'Cattleya',
    info: 'An orange orchid that radiates warmth and energy, native to the vibrant landscapes of Mexico.',
    cost: 120
  },
  {
    id: '9',
    name: 'Ruby Orchid',
    rating: 5,
    isSpecial: true,
    image: 'https://litiflorist.com/upload/1623048776856.png',
    color: 'red',
    origin: 'Sri Lanka',
    category: 'Cymbidium',
    info: 'A rich ruby-red orchid from Sri Lanka, cherished for its luxurious appearance and longevity.',
    cost: 430
  },
  {
    id: '10',
    name: 'Azure Bliss',
    rating: 4.5,
    isSpecial: false,
    image: 'https://static.wixstatic.com/media/cedc8a_a7c43815413f4eed92e37bbec1943f99~mv2.jpg/v1/fill/w_480,h_480,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/cedc8a_a7c43815413f4eed92e37bbec1943f99~mv2.jpg',
    color: 'blue',
    origin: 'Malaysia',
    category: 'Vanda',
    info: 'A serene blue orchid with calming tones, often found in the lush environments of Malaysia.',
    cost: 210
  },
  {
    id: '11',
    name: 'Sunset Glow',
    rating: 4.2,
    isSpecial: false,
    image: 'https://orchidroots.com/static/utils/images/hybrid/hyb_000018601_100109783.jpg',
    color: 'yellow',
    origin: 'Vietnam',
    category: 'Dendrobium',
    info: 'A yellow orchid that captures the beauty of a sunset, native to the picturesque landscapes of Vietnam.',
    cost: 30
  },
  {
    id: '12',
    name: 'Crimson King',
    rating: 5,
    isSpecial: true,
    image: 'https://theorchidpatio.com.au/cdn/shop/files/spc_000021117_000002595.jpg?v=1684227429',
    color: 'dark red',
    origin: 'Philippines',
    category: 'Phalaenopsis',
    info: 'A majestic orchid with deep crimson hues, symbolizing power and beauty.',
    cost: 75
  },
  {
    id: '13',
    name: 'Amethyst Dream',
    rating: 4.9,
    isSpecial: false,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTicr1SZMttLSNo7U0JLAlnLTlLPU6ERq9HgQ&s',
    color: 'purple',
    origin: 'China',
    category: 'Vanda',
    info: 'A dreamy purple orchid that captivates with its vibrant amethyst tones, popular in China.',
    cost: 29
  },
  {
    id: '14',
    name: 'Golden Hour',
    rating: 4.6,
    isSpecial: true,
    image: 'https://preview.redd.it/my-favorite-phal-during-golden-hour-v0-6k57jbhhg6ia1.jpg?width=640&crop=smart&auto=webp&s=76be70e9c9e95c402fd75686ee4b5db086ab1dc5',
    color: 'yellow',
    origin: 'Indonesia',
    category: 'Cymbidium',
    info: 'A glowing yellow orchid that reflects the beauty of golden hour, hailing from Indonesia.',
    cost: 96
  },
  {
    id: '15',
    name: 'Mystic Orchid',
    rating: 5,
    isSpecial: true,
    image: 'https://cdn11.bigcommerce.com/s-o2rv5d0tql/product_images/uploaded_images/orchid-blue-mystique.jpg',
    color: 'blue',
    origin: 'Costa Rica',
    category: 'Oncidium',
    info: 'A mysterious blue orchid with an enchanting appearance, found in Costa Rica.',
    cost: 55
  },
  {
    id: '16',
    name: 'Pink Elegance',
    rating: 4.3,
    isSpecial: false,
    image: 'https://images.stockcake.com/public/a/2/6/a26ace18-92ca-4ec4-a393-a5bf85241454_large/elegant-orchid-bloom-stockcake.jpg',
    color: 'pink',
    origin: 'South Korea',
    category: 'Cattleya',
    info: 'A delicate pink orchid with an elegant charm, native to South Korea.',
    cost: 400
  }
];


